# -*- coding: utf-8 -*-
"""Timeconversion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EudUxOSNQozVd-UX-PBmNVnig2ZY8RRv
"""

#Given a time in 12-hour AM/PM format, convert it to military (24-hour) time.
s = '12:45:54PM'

c = s[-2:]

if c == 'AM':
  if s[:2] == '12':
      b = s[:-2]
      a = b.split(':',)
      a[0] = '00'
      s = ":".join(a)
  else:
      b = s[:-2]
      a = b.split(':',)
      s = ":".join(a)
else:
  if s[:2] == '12':   
    b = s[:-2]
    a = b.split(':',)
    s = ":".join(a)
  else:
    b = s[:-2]
    a = b.split(':',)
    a[0] = str(int(a[0])+12)
    s = ":".join(a)
s